### ISSUE TITLE
Get specs with Doc for Var

### ISSUE THREAD

**Issue by gerred** [mauricioszabo/atom-chlorine#100]
It'd be nice using the Doc for Var functionality if it matched with (doc ...) and showed any known specs!

**Comment by mauricioszabo** [comment]
Yes, the thing is I wasn't being able to make it work with ClojureScript, that's why it doesn't match the `doc` from the REPL.

While I was reorganizing the project, I've talked with people from other projects and I'll use Orchard (so `doc` will work in Clojure and ClojureScript, and it'll be a little bit richer than it currently is) and will fallback to the current implementation.

I'm currently tracking this issue here: https://github.com/mauricioszabo/repl-tooling/projects/1#card-26440959

**Comment by mauricioszabo** [comment]
Fixed on version 0.3.6
