### ISSUE TITLE
Add support for using *1, *2, *3, and *e

### ISSUE THREAD

**Issue by KevinSjoberg** [mauricioszabo/atom-chlorine#229]
When you evaluate a block, it would be nice to be able to use `*1`, `*2` and `*3` and `*e` respectively to reference return values and the last exception.

Taken from the [Clojure docs](https://clojure.org/reference/repl_and_main):

> Several special vars are available when using the REPL:
> 
> *1, *2, *3 - hold the result of the last three expressions that were evaluated
> *e - holds the result of the last exception.

It seems to be supported by most REPLs.

```clojure
(+ 1 1) ; When evaluated returns 2
(println *1) ; When evaluated prints 2 and returns nil (given the prior form was evaluated first).
```

I'd be happy to contribute a small amount to make this happen if you're interested in pursuing it. 🙂

**Comment by KevinSjoberg** [comment]
Investigating this a bit further, I realise that it might not be technically possible.

Given that `echo "(+ 1 1)" | nc 0 5555` returns `user=> 2` and `echo "(println *1)" | nc 0 5555` returns `nil` immediately afterwards. Perhaps it's a limitation of the Socket REPL?

**Comment by mauricioszabo** [comment]
No, it's not really possible.  A single "eval top block" can issue one to three commands to the REPL, so the value of these vars are not bound to last evaluation. Also, there's no `*e` on most REPLs - most exceptions are captured and serialized for Chlorine to capture...

I'll probably add an entry on the FAQ regarding these vars :)

**Comment by KevinSjoberg** [comment]
@mauricioszabo I see, that makes sense. 🙂 So am I right in assuming Chlorine does one-off evaluations to the Socket REPL instead of having an ongoing connection to it and that's why it's really not technically possible to achieve that?

**Comment by mauricioszabo** [comment]
No, it does have an ongoing connection. The problem is that when you evaluate anything, Chlorine tries to detect:

1. Does this editor have a filename associated to it?
2. Does it have a `ns` form?

If `1` is true, it'll send a command to set the filename (binding `*1` to it);
If `2` is true, it'll send a command to set the namespace (again, binding `*1`)
Then, it'll send the eval command (once again, binding `*1`).

Now, if `1` and `2` are true (which they are, most of the time), everytime you send an evaluation you'll have `*1` and `*2` bound to `nil` and the current namespace (that's what the REPL returns when you set a filename and namespace). This means that "original `*1`" (the one that contains the evaluation result) is now `*3`.

You can check this yourself by trying to eval something, then evaluating `*3`. You'll see that it indeed contains the result of last eval; and that `*1` probably contains `nil`, and `*2` contains an instance to `clojure.lang.Namespace`

![image](https://user-images.githubusercontent.com/138037/103283065-52fb2b80-49b6-11eb-84a4-c650c08282e6.png)

**Comment by mauricioszabo** [comment]
BTW, a simple correction: Chlorine will try to detect the `ns` FIRST then the filename. The reason is that when it detects the filename it also sets the right row, so if we send the `in-ns` command first it'll mess the current row

**Comment by KevinSjoberg** [comment]
I see. That makes sense. So, it "works" but not in the way you would expect, making it less useful? I tried out the example and it worked just like you said it would. However, the example below didn't set `*1`, `*2` and `*3` to anything, which made me a bit confused again.

<img width="598" alt="Screenshot 2020-12-29 at 13 20 49" src="https://user-images.githubusercontent.com/503025/103283460-e9404900-49d8-11eb-88a8-380355142560.png">

**Comment by mauricioszabo** [comment]
Do you have a `ns` form on this editor? This could explain why `*2` is bound to nothing.

As for the `nil` in `*3`, it's probably because you eval'ed `*1` first (then making it `nil`). Also, you don't have a filename but Chlorine will still try to set the current row, binding it to `nil`

The current code that does handle evals in Chlorine starts here: https://github.com/mauricioszabo/repl-tooling/blob/master/src/repl_tooling/repl_client/clojure.cljs#L95-L96 

and goes to here: https://github.com/mauricioszabo/repl-tooling/blob/master/src/repl_tooling/repl_client/clojure.cljs#L40-L48

**Comment by KevinSjoberg** [comment]
Thanks for taking the time to explain this so throughly. It's really appreciated. 🙂

**Comment by KevinSjoberg** [comment]
Sorry for bringing this up again, but when I woke up this morning, I realised I didn't understand the following:

> If 1 is true, it'll send a command to set the filename (binding *1 to it);
If 2 is true, it'll send a command to set the namespace (again, binding *1)
Then, it'll send the eval command (once again, binding *1).

Isn't `*1` always pointing to value returned by the last expression? So even if you send multiple commands before evaluating the actual form, shouldn't `*1` still be assigned the result of that expression?

**Comment by KevinSjoberg** [comment]
Alright, so I dove into this myself using `socat` as a proxy.

Having a file with the following contents:

```clojure
(+ 1 1)
(println *1 *2)
```

and evaluating each expression in order, prints `*1` as `nil` and `*2` as `2`. Looking at the `socat` output I can see that `(+ 1 1)` is being evaluated as:

```clojure
(do
(+ 1 1)
)
```

Is this perhaps related to what we discussed in #228? If so, would this not be a problem whenever you get to looking into Pathom?

**Comment by mauricioszabo** [comment]
> So how come *1 isn't the value of whatever was being evaluated

It is - but the problem is that when you evaluate something in Chlorine, it'll send other commands before your eval. So it'll be re-bind to the result of previous command - for example, the "set filename and/or row"

**Comment by KevinSjoberg** [comment]
@mauricioszabo perhaps I misunderstood how the REPL bind the dynamic variables, but anything before my eval shouldn't be a problem since `*1` is bound to the **last** result. I'm sorry if I'm asking a lot of questions, just trying to wrap my head around this.

**Comment by mauricioszabo** [comment]
Ok, so the thing is: if you don't have a `ns` form on your editor, Chlorine will try to run a code to set the current row. Let's suppose this code is called `(set-row <some-number>)`. So, if you're on the line 20 of the editor, this is what will be run:

```clojure
; Evaling (+ 1 2)
(set-row 19) ; Binds *1 to nil

(do
(+ 1 2)); Binds *2 to nil, and *1 to 3
```

Now, on the second evaluation, if you eval `*1`:

```clojure
(set-row 19) ; Binds *1 to nil, *2 to 3, and *3 to nil

(do
*1) ; *1 is nil, so it'll bind *1 to nil, *2 to nil, and *3 to 3

**Comment by KevinSjoberg** [comment]
@mauricioszabo thanks a lot, it finally clicked! Really appreciate you taking the time to explain this in detail. 🙂
