### ISSUE TITLE
[FEATURE] Direct interaction with REPL

### ISSUE THREAD

**Issue by m0rtis0** [mauricioszabo/atom-chlorine#233]
Hi everyone,
I am just trying out Chlorine and it is awesome!
(My favourite is the ability to eval on save)
However, i am missing one use case from the extension: The ability to directly input into the REPL for debugging
while debugging, I find it somewhat inconvenient to create a new file / section in the project just to print out the result of some variable.
Maybe I am missing something here, but this would really be a game changer. For people that consider switching from the outdated Proto-REPL this would be amazing as well.

**Comment by seancorfield** [comment]
As Stu Halloway says "I'm completely baffled when I see people typing into the REPL". Chlorine's lack of input for the REPL is a feature, not a bug. You shouldn't type into the REPL: if you're debugging something in a program, put a Rich Comment Form `(comment ..)` in a source file of that program and evaluate forms from inside that -- that will be a good place to keep notes as you are debugging, as well. It's what Rich Hickey does and recommends, it's what Stu does and recommends. It's also what Eric Normand recommends in his excellent REPL-Driven Development course.

**Comment by m0rtis0** [comment]
Okay, I can understand this viewpoint, thanks for the insight

**Comment by mauricioszabo** [comment]
I thought I answered this issue, but it seems that I didn't...

There's another think: Chlorine needs some info from the current editor to know it it'll evaluate ClojureScript or Clojure. Also, when you eval code in the editor, namespaces can change so to support this feature I would have to listen to the REPL, update the current namespace on the REPL window (otherwise people would see strange issues with unknown var names/etc), and other awkward situations...
