### ISSUE TITLE
Version 0.1.13 is awesome

### ISSUE THREAD

**Issue by ChrisBronkhorst** [mauricioszabo/atom-chlorine#99]
@mauricioszabo, 0.1.13 has been a huge improvement for me.  I really love the truncated inline eval results.  This has allowed me to stop worrying about evaluations which return large result sets.  I also really like how the console is much less spammy, and only shows errors and explicit prints.

This last commit has really put it over the top of proto-repl for me.  Thanks for all of the hard work.

**Comment by mauricioszabo** [comment]
Thanks, great to know!

The only thing is that I was thinking on reverting the old console because
some features are not working (like, when you refresh and your code have an
error it doesn't show anywhere with the new console). But this would
probably break your experience...

I'll post a screenshot or a video of the new console and then I want some
opinions. Maybe I can add a config for the console kind or something. Do
you have any channel where we could discuss this feature?

**Comment by ChrisBronkhorst** [comment]
Personally, I was trying to find a better channel than github issues to say thanks on.  I'm happy to chat on the chlorine channel on clojurians.slack
